// Test customer profile — realistic Indian applicant data
const TEST_CUSTOMER = {
  firstName:        'Ashok',
  middleName:       '',
  lastName:         'kumar',
  fullName:         'Ashok kumar',
  fatherName:       'Awadhesh Singh',
  motherName:       'Shankuntala devi',
  husbandName:      '',
  dob:              '1995-05-15',
  gender:           'Male',
  category:         'OBC-NCL',
  religion:         'Hindu',
  nationality:      'Indian',
  maritalStatus:    'Unmarried',
  annualIncome:     '87578',
  identMark1:       'A mole on shoulder',
  identMark2:       'Scar on left hand',
  employed:         'No',
  empExchangeNo:    '',
  criminalCase:     'No',
  debarred:         'No',
  emailId:          'ashok@test.com',
  mobileNumber:     '9999988888',
  altMobile:        '9999977777',
  permAddr1:        'Village Agiaon',
  permAddr2:        'Post Agiaon',
  permPO:           'Agiaon',
  permPS:           'Agiaon',
  permDistrict:     'Bhojpur',
  permState:        'Bihar',
  permPin:          '802201',
  aadhaarNumber:    '123456789012',
  panNumber:        'ABCDE1234F',
  voterId:          'ABC1234567',
  passportNumber:   'N1234567',
  dlNumber:         'BR012345678901',
  bankAcc:          '123456789012345',
  bankIFSC:         'SBIN0001234',
  bankName:         'SBI',
  bankBranch:       'Bhojpur',
  isPwd:            'No',
  disabilityType:   '',
  disabilityPercent:'',
  pwdCertNo:        '',
  domicileCertNo:   'DOM123456',
  domicileIssueDate:'2020-01-15',
  domicileAuthority:'Tehsildar, Bhojpur',
  casteCertNo:      'CASTE123456',
  casteIssueDate:   '2020-02-10',
  casteAuthority:   'Tehsildar',
  casteIssueDistrict:'Bhojpur',
  incomeCertNo:     'INC123456',
  incomeIssueDate:  '2020-03-20',
  tenthBoard:       'BSEB',
  tenthYear:        '2010',
  tenthPercent:     '75',
  tenthObtained:    '450',
  tenthTotal:       '600',
  tenthRoll:        '101234',
  tenthCertNo:      'CERT101234',
  tenthDivision:    'First Division',
  twelfthBoard:     'BSEB',
  twelfthYear:      '2012',
  twelfthPercent:   '72',
  twelfthObtained:  '432',
  twelfthTotal:     '600',
  twelfthRoll:      '201234',
  twelfthCertNo:    'CERT201234',
  twelfthStream:    'Science',
  gradDegree:       'B.Tech',
  gradUniv:         'RGPV Bhopal',
  gradYear:         '2016',
  gradPercent:      '68',
  gradRoll:         '0813IT101234',
  gradIssueDate:    '2016-06-30',
  pgDegree:         'M.Tech',
  pgUniv:           'NIT Patna',
  pgYear:           '2018',
  pgPercent:        '78',
  pgRoll:           '1601MT1234',
};

module.exports = TEST_CUSTOMER;
